[build]
  command = "mkdir -p public && cp -r src/web/static/* public/ && python build_css.py"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[dev]
  framework = "#custom"
  command = "python main.py web"
  port = 8001
  targetPort = 8001

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200